# Generated by Django 5.2.3 on 2025-07-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment', 'student')},
        ),
    ]
