# Generated by Django 5.2.3 on 2025-07-31 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('schools', '0002_alter_classroom_options_alter_classroom_teachers'),
        ('students', '0001_initial'),
        ('subjects', '0002_subject_teacher_alter_subject_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyassessment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examassessment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='examassessment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyassessment',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.AddField(
            model_name='examassessment',
            name='semester',
            field=models.CharField(choices=[('1', 'Birinci yarımil'), ('2', 'İkinci yarımil')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyassessment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyassessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examassessment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examassessment',
            name='exam_type',
            field=models.CharField(choices=[('MS', 'Kiçik Summativ'), ('BS', 'Böyük Summativ'), ('YI', 'Yekun İllik')], max_length=2),
        ),
        migrations.AlterField(
            model_name='examassessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='examassessment',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'semester', 'exam_type'), name='unique_student_subject_exam'),
        ),
        migrations.RemoveField(
            model_name='dailyassessment',
            name='note',
        ),
    ]
