# Generated by Django 5.2.3 on 2025-07-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_dailyassessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examassessment',
            name='unique_student_subject_exam',
        ),
    ]
