# Generated by Django 5.2.3 on 2025-08-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_examassessment_unique_student_subject_exam'),
        ('schools', '0002_alter_classroom_options_alter_classroom_teachers'),
        ('students', '0001_initial'),
        ('subjects', '0002_subject_teacher_alter_subject_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_type', 'BS')), fields=('student', 'subject', 'semester', 'exam_type'), name='unique_bs_per_semester'),
        ),
    ]
