# Generated by Django 5.2.3 on 2025-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation_email'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subjects.subject'),
        ),
    ]
