# Generated by Django 5.2.3 on 2025-07-06 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['school__name', 'name']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='teaching_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
