# Generated by Django 5.2.3 on 2025-08-12 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_classroom_teachers_teachingassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
