# Generated by Django 5.2.3 on 2025-08-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
