# Generated by Django 5.2.3 on 2025-08-01 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='usernotification',
            old_name='received_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
