# Generated by Django 5.2.3 on 2025-08-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
